RECIPES_PATH = "./cuisine_preprocess.csv"
TFIDF_ENCODING_PATH = "./tfidf/tfidf_encodings.pkl"
TFIDF_MODEL_PATH = "./tfidf/tfidf.pkl"
NUTRITION_NORMALISED = "./Nutrition_Normalized.csv"
CUISINE_ENCODING_PATH = "./tfidf/cuisine_encodings.pkl"
CUISINE_MODEL_PATH = "./tfidf/cuisine.pkl"
TEST = "./test.csv"
NUTRI = "./nutrition_recommend.py"